# Generated by Django 5.2.7 on 2025-11-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_alter_tournament_end_date_and_more'),
        ('players', '0002_alter_player_options_player_best_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_won', to='players.player'),
        ),
    ]
