# Generated by Django 5.2.7 on 2025-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('category', models.CharField(choices=[('MS', 'Men Singles'), ('WS', 'Women Singles'), ('MD', 'Men Doubles'), ('WD', 'Women Doubles'), ('XD', 'Mixed Doubles')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
